export const LOGIN = "LOGIN";
export const REGISTER="REGISTER";
export const VERIFY_ACCOUNT="VERIFY_ACCOUNT";
export const FORGOT_PASSWORD="FORGOT_PASSWORD";
export const RESET_PASSWORD="RESET_PASSWORD";
export const CREATE_ORGANIZATION="CREATE_ORGANIZATION";
export const FETCH_ORGANIZATION="FETCH_ORGANIZATION";
export const FETCH_ORGANIZATIONS="FETCH_ORGANIZATIONS";
export const FETCH_TEAM_MEMBERS="FETCH_TEAM_MEMBERS";
export const CREATE_TEAM_MEMBER="CREATE_TEAM_MEMBER";

